name: 'IAM Policy Update'
branding:
  icon: book-open
  color: purple
description: 'Update the selected IAM policy JSON with a new one'
inputs:
  policyarn:
    description: 'The ARN of the policy to modify'
    required: true
    default: ''
  policyfile:
    description: 'The location of the new policy file'
    required: true
    default: ''
outputs:
  newpolicy:
    description: "Policy Modified Message"
    value: The Policy ${{ inputs.policyarn }} were updated successfully with the new policy from file ${{ inputs.policyfile }} 
runs:
  using: "composite"
  steps:
    - run: echo "Applying the new policy file ${{ inputs.policyfile }}"
      shell: bash
    - run: cat ${{ inputs.policyfile }}
      shell: bash
    - run: |
        aws iam create-policy-version 
        --policy-arn ${{ inputs.policyarn }}
        --policy-document file://${{ inputs.policyfile }}
        --set-as-default
      shell: bash