name: 'IAM Policy Update'
branding:
  icon: book-open
  color: purple
description: 'Update the selected IAM policy JSON with a new one'
inputs:
  policy-arn:
    description: 'The ARN of the policy to modify'
    required: true
    default: ''
  policy-file:
    description: 'The location of the new policy file'
    required: true
    default: ''
outputs:
  newpolicy:
    description: "Policy Modified Message"
    value: The Policy ${{ inputs.policy-arn }} were updated successfully with the new policy from file ${{ inputs.policy-file }} 
runs:
  using: "composite"
  steps:
    - run: echo "Applying the new policy file ${{ inputs.policy-file }}"
      shell: bash
    - run: cat ${{ inputs.policy-file }}
      shell: bash
    - run: |
        aws iam create-policy-version --policy-arn ${{ inputs.policy-arn }} --policy-document file://${{ inputs.policy-file }} --set-as-default
      shell: bash
    - run: echo "Finished applying new Policy - ${{ inputs.policy-file }}, To ARN - ${{ inputs.policy-arn }}."
      shell: bash